AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  testFunction1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./testFunction1/
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld1:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /func1
            Method: get
  getRecipientMessages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./getRecipientMessages/
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetRecipientMessages:
          Type: Api
          Properties:
            Path: /getRecipientMessages
            Method: GET
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: 'Message'
  sendMessage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./sendMessage/
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SendMessage:
          Type: Api
          Properties:
            Path: /sendMessage
            Method: POST
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: 'Message'
  
      
      

