name: Deploy to lambda
on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/main.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Validate deployment spec
        run: sam validate
      - name: Package backend files
        run: |
          cd backend
          sam build --use-container
      - name: Deploy package to AWS
        run: |
          cd backend
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3
